In [10]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([100,150,125,140,160])

In [3]:
arr.var()

440.0

In [4]:
arr.std()

20.97617696340303

In [6]:
#geometric mean - avg growth rate
import numpy as np
x = np.array([1,2,2])
p = 1/len(x)
res = np.prod(x) # multiply all elements in x
print(np.power(res,p))

1.5874010519681994


In [7]:
#harmonic mean - avg speed
import scipy.stats as st
data = np.array([25,30])
st.hmean(data)

27.272727272727273

In [15]:
class1 = np.array([95,84,73,62,41,58,79])
class2 = np.array([89,74,83,72,61,48,81])

In [16]:
class1.corr(class2)

AttributeError: 'numpy.ndarray' object has no attribute 'corr'

In [17]:
pd.corr(class1, class2)

AttributeError: module 'pandas' has no attribute 'corr'

In [18]:
np.corrcoef(class1,class2)

array([[1.        , 0.76817304],
       [0.76817304, 1.        ]])

In [19]:
class1 = class1 - 1

In [20]:
np.corrcoef(class1,class2)

array([[1.        , 0.76817304],
       [0.76817304, 1.        ]])

In [21]:
class1

array([94, 83, 72, 61, 40, 57, 78])

In [22]:
from scipy.stats import poisson

In [25]:
lamb = 2
poisson.pmf(5,lamb)

0.03608940886309672

In [27]:
from scipy.stats import norm
norm.ppf(0.70)

0.5244005127080407

In [29]:
from scipy.stats import norm
norm.ppf(0.75)

0.6744897501960817

In [30]:
from scipy.stats import norm
norm.ppf(0.65)

0.38532046640756773

In [33]:
from scipy.stats import norm
norm.cdf(1.25)

0.8943502263331446

In [34]:
from scipy.stats import norm
norm.cdf(2.25,loc=4,scale=2)

0.19078695285251068

In [36]:
from scipy.stats import norm
1-norm.cdf(3.12,loc=7,scale=3)

0.9020521016707304

In [37]:
from scipy.stats import expon
lamb = 2
expon.cdf(1, scale =1/lamb)

0.8646647167633873

In [39]:
from scipy.stats import expon
lamb = 2
1-expon.cdf(2, scale =1/lamb)

0.01831563888873422

In [40]:
from scipy.stats import ttest_1samp
new_w =[50.5, 47.3, 56.2, 48.9, 51.3, 49.7, 55.2]
t,p = ttest_1samp(new_w, 50)

In [42]:
print(t,p/2)

1.051642529556478 0.16673118243067742


In [45]:
from scipy.stats import ttest_ind
med1 = [89,90,91,95,101,105,107]
med2 = [67,78,79,92,96,98]
t,p = ttest_ind(med1,med2,equal_var = False)

In [46]:
print (t,p/2)

2.068503037352276 0.036178248423517696
