In [1]:
import torch
import torch.nn.functional as F

C:\Users\maidu\.conda\envs\nlp\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
#x = torch.tensor([[[0., 1., 2.], [3., 4., 5.], [6., 7., 8.]]], requires_grad=True)

In [3]:
x = torch.tensor([[[0., 1., 2.], [3., 4., 5.], [6., 7., 8.]],
              [[9., 10., 11.], [12., 13., 14.], [15., 16., 17.]],
              [[18., 19., 20], [21., 22., 23.], [24., 25., 26.]]], requires_grad=True)

In [4]:
x

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.]],

        [[ 9., 10., 11.],
         [12., 13., 14.],
         [15., 16., 17.]],

        [[18., 19., 20.],
         [21., 22., 23.],
         [24., 25., 26.]]], requires_grad=True)

In [5]:
x.transpose(1, 2)

tensor([[[ 0.,  3.,  6.],
         [ 1.,  4.,  7.],
         [ 2.,  5.,  8.]],

        [[ 9., 12., 15.],
         [10., 13., 16.],
         [11., 14., 17.]],

        [[18., 21., 24.],
         [19., 22., 25.],
         [20., 23., 26.]]], grad_fn=<TransposeBackward0>)

In [6]:
raw_weights = torch.bmm(x, x.transpose(1,2))


In [7]:
#apply softmax ,row wise
weights = F.softmax(raw_weights, dim=2)


In [8]:
y = torch.bmm(weights, x)

In [9]:
y

tensor([[[ 5.9996,  6.9996,  7.9996],
         [ 6.0000,  7.0000,  8.0000],
         [ 6.0000,  7.0000,  8.0000]],

        [[15.0000, 16.0000, 17.0000],
         [15.0000, 16.0000, 17.0000],
         [15.0000, 16.0000, 17.0000]],

        [[24.0000, 25.0000, 26.0000],
         [24.0000, 25.0000, 26.0000],
         [24.0000, 25.0000, 26.0000]]], grad_fn=<BmmBackward0>)