In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
csv_in = 'wine-modified.csv'

# To show all rows and columns in the results 
pd.options.display.max_columns=999
pd.options.display.max_rows=999

In [3]:
df = pd.read_csv(csv_in, delimiter=',', skiprows=0, header=0)
print(df.shape)
print(df.info())
display(df.head())

(178, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Class                         178 non-null    int64  
 1   Alcohol                       178 non-null    float64
 2   Malic_acid                    178 non-null    float64
 3   Ash                           178 non-null    float64
 4   Alcalinity_of_ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64  
 6   Total_phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid_phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color_intensity               178 non-null    float64
 11  Hue                           178 non-null    float64
 12  OD280/OD315_of_diluted_wines  178 non-null    float64


Class  Alcohol  Malic_acid   Ash  Alcalinity_of_ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Total_phenols  Flavanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280/OD315_of_diluted_wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [4]:
df.cov()

Class     Alcohol  Malic_acid        Ash  \
Class                           0.600679   -0.206515    0.379039  -0.010555   
Alcohol                        -0.206515    0.659062    0.085611   0.047115   
Malic_acid                      0.379039    0.085611    1.248015   0.050277   
Ash                            -0.010555    0.047115    0.050277   0.075265   
Alcalinity_of_ash               1.340364   -0.841093    1.076332   0.406208   
Magnesium                      -2.315495    3.139878   -0.870780   1.122937   
Total_phenols                  -0.348835    0.146887   -0.234338   0.022146   
Flavanoids                     -0.656091    0.192033   -0.458630   0.031535   
Nonflavanoid_phenols            0.047177   -0.015754    0.040733   0.006358   
Proanthocyanins                -0.221413    0.063518   -0.141147   0.001516   
Color_intensity                 0.477339    1.028283    0.644838   0.164654   
Hue                            -0.109368   -0.013313   -0.143326  -0.004682   
OD280/OD315_of_diluted_wines   -0.433737    0.041698   -0.292447   0.000762   
Proline                      -154.667651  164.567185  -67.548867  19.319739   

                              Alcalinity_of_ash    Magnesium  Total_phenols  \
Class                                  1.340364    -2.315495      -0.348835   
Alcohol                               -0.841093     3.139878       0.146887   
Malic_acid                             1.076332    -0.870780      -0.234338   
Ash                                    0.406208     1.122937       0.022146   
Alcalinity_of_ash                     11.152686    -3.974760      -0.671149   
Magnesium                             -3.974760   203.989335       1.916470   
Total_phenols                         -0.671149     1.916470       0.391690   
Flavanoids                            -1.172083     2.793087       0.540470   
Nonflavanoid_phenols                   0.150422    -0.455563      -0.035045   
Proanthocyanins                       -0.377176     1.932832       0.219373   
Color_intensity                        0.145024     6.620521      -0.079998   
Hue                                   -0.209118     0.180851       0.062039   
OD280/OD315_of_diluted_wines          -0.656234     0.669308       0.311021   
Proline                             -463.355345  1769.158700      98.171057   

                              Flavanoids  Nonflavanoid_phenols  \
Class                          -0.656091              0.047177   
Alcohol                         0.192033             -0.015754   
Malic_acid                     -0.458630              0.040733   
Ash                             0.031535              0.006358   
Alcalinity_of_ash              -1.172083              0.150422   
Magnesium                       2.793087             -0.455563   
Total_phenols                   0.540470             -0.035045   
Flavanoids                      0.997719             -0.066867   
Nonflavanoid_phenols           -0.066867              0.015489   
Proanthocyanins                 0.373148             -0.026060   
Color_intensity                -0.399169              0.040121   
Hue                             0.124082             -0.007471   
OD280/OD315_of_diluted_wines    0.558262             -0.044469   
Proline                       155.447492            -12.203586   

                              Proanthocyanins  Color_intensity        Hue  \
Class                               -0.221413         0.477339  -0.109368   
Alcohol                              0.063518         1.028283  -0.013313   
Malic_acid                          -0.141147         0.644838  -0.143326   
Ash                                  0.001516         0.164654  -0.004682   
Alcalinity_of_ash                   -0.377176         0.145024  -0.209118   
Magnesium                            1.932832         6.620521   0.180851   
Total_phenols                        0.219373        -0.079998   0.062039   
Flavanoids                           0.373148        -0.

In [37]:
a = np.array([[1,4],[9,1]])
print(a)
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)


[[1 4]
 [9 1]]
[ 7. -5.]
[[ 0.5547002  -0.5547002 ]
 [ 0.83205029  0.83205029]]


In [38]:
A = np.array([[3,2],[3,-2]])
eigenValues, eigenVectors = np.linalg.eig(A)

idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]
print(eigenValues)
print('')
print(eigenVectors)

[ 4. -3.]

[[ 0.89442719 -0.31622777]
 [ 0.4472136   0.9486833 ]]


## You want the columns, not the rows.



In [41]:
np.array([0.89442719, 0.4472136])*4

array([3.57770876, 1.7888544 ])

In [44]:
eigenvector = np.array([0.89442719, 0.4472136])
np.dot(A,eigenvector)

array([3.57770877, 1.78885437])